### ISSUE TITLE
[FEATURE]: Share Button for facebook

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#12]
Create an interactive share to Facebook button.
don't forget to add up the quote with it, so that the quote with author name, can be share to fakebook.

**Comment by rohits-web03** [comment]
#### Hello @Shariar-Hasan ,
#### While trying to add the facebook share button with the specified feature you mentioned, I found that we can only share a post url with that button not any post title.This is mentioned in Facebook(meta)'s website
#### That means user can share the link of QuoteVerse but not the quote with it directly.In order to share the quote they have to manually copy and paste the quote when the facebook share post tab will open.
#### Here's docs link for the share button: [share button](https://developers.facebook.com/docs/plugins/share-button/)

**Comment by rohits-web03** [comment]
#### Other social media platforms allow websites to share post title(content from website) along with URL with their share button but not facebook i think.
#### If that's okay with you,you can assign me this issue.
#### I will then add the facebook share button for issue #12

**Comment by Shariar-Hasan** [comment]
> #### Hello @Shariar-Hasan ,
> #### While trying to add the facebook share button with the specified feature you mentioned, I found that we can only share a post url with that button not any post title.This is mentioned in Facebook(meta)'s website
> #### That means user can share the link of QuoteVerse but not the quote with it directly.In order to share the quote they have to manually copy and paste the quote when the facebook share post tab will open.
> #### Here's official docs link for the share button: [share button](https://developers.facebook.com/docs/plugins/share-button/)

oh i see, thanks for the clarification.



> #### Other social media platforms allow websites to share post title(content from website) along with URL with their share button but not facebook i think.
> #### If that's okay with you,you can assign me this issue.
> #### I will then add the facebook share button for issue #12

Yeah sure,
just follow:
- star the repo,
- make a clone of the repo
- do neccessary changes
- make a PR

**Comment by rohits-web03** [comment]
#### Kindly check pull request #30
